### ISSUE TITLE
No redistributables (except libglfw, liblua, libopenal) :P

### ISSUE THREAD

**Issue by Mailaender** [andykorth/Pencil.Gaming#35]
> A feature that Pencil.Gaming has over most other C# gaming libraries, is that users do not need to install any redistributables besides Mono/.NET!

https://github.com/andykorth/Pencil.Gaming/tree/master/Pencil.Gaming/natives32-glfw2 You just bundled the native dependencies, but advertise it as if this was a pure C# no wrapper solution which is confusing.

**Comment by andykorth** [comment]
The word "redistributables" specifically refers to required libraries that the user is required to install into their system and are not provided bundled with the software the end user downloads. Minimizing restributables is important because they are very inconvenient for the user to install. That paragraph was written by someone who is mostly a Windows user, so it's from their perspective.

Often, Windows software comes with standalone installer programs. These programs often ensure that the proper system libraries are installed. These often include redistributables such as Microsoft C++ runtime, .Net runtimes of various versions, direct X, etc. Apparently that stuff doesn't just come installed on fresh windows installs.

Some more information:
http://superuser.com/questions/173403/why-are-there-so-many-different-visual-c-redistributables
https://msdn.microsoft.com/en-us/library/aa372856(v=vs.85).aspx
https://askleo.com/do_i_need_these_microsoft_visual_c_redistributables/

This specific feature of Pencil.Gaming is highlighted, since it's common to require users of your end product to install a bunch of other stuff. 

Bundling native dependencies is a good solution, especially if they are small. Making a purely C# crossplatform solution that supports things like native windowing is almost certainly impossible. Apple doesn't provide C# Cocoa windowing calls, for example. 

If you have suggestions on how to clarify that, feel free to make a pull request! 

Perhaps:
"users do not need to install any redistributables besides Mono/.NET, and binaries are provided for bundle-able dependencies."

**Comment by Mailaender** [comment]
We did essentially the same with something OpenTK based only that we don't store the binaries in our source code management, but rather download them at build time from repositories like NuGet. https://github.com/OpenRA/OpenRA/tree/bleed/thirdparty

After my recent refactor https://github.com/OpenRA/OpenRA/pull/8632 I will try to give your framework a try. It sounds very promising.
