### ISSUE TITLE
Create working version 1.0

### ISSUE THREAD

**Issue by antonijn** [andykorth/Pencil.Gaming#51]
**I have time available in the weekend of July 15th which I could spend on this.**

Some maintenance is obviously long overdue, and I propose some changes (Andy, you'll have to okay them). This is the first of a number of issues I'll open that I'll mark with ~"version-2"~ milestone v2, since the end goal is to create a version 2.0 of the library (fundamentally incompatible with 1.0, mostly in a cruft-removal way).

The first step would be to create a working "old" version of the library: version 1.0 (perhaps 1.1?). This'll mark some classes and functions as deprecated, notably some things that are out of the scope of a simple gaming library like Pencil.Gaming ought to be.

I propose deprecation (for removal in v2) of:
- `GL.Utils`
- `Pencil.Gaming.Scripting`
- GLFW 2
- NVorbis

I also propose tagging v1.0 when it's done, and having it as the last commit of the master branch until v2.0 is ready (shouldn't take longer than a weekend, really). v2.0 development would be on a [separate unstable "develop" branch](http://nvie.com/posts/a-successful-git-branching-model/). The master branch should, in future, only contain stable versions of the library. In this branching model it could be nice to set the default GitHub branch to the unstable "develop" branch, that's up to Andy.

EDIT: Derp, GitHub has Milestones ofc, I've added a v2 milestone instead of a version-2 label.

**Comment by andykorth** [comment]
This sounds like good plan, I wholeheartedly support removal of the Lua scripting stuff and glfw 2 at this point. Likewise with the removal of the other two. If you want to tag what's currently in the repository and move directly to the removal of the old cruft in version 2.0, I think that'd be great also. 

I would expect the proposed v2.0 to be considered "stable" pretty quickly. I think we would want to direct new users to use that as soon as it's done, especially given the infrequency of changes to the library.

If I recall correctly, GL.Utils is mostly just some texture loading and a very simple .obj parser for meshes. Since GLFW 3 doesn't provide any of that, I think the texture loading functionality might live on best on the wiki, as an example to help people to get started. obj loading is perhaps less important. ( it's been a few years, but System.Drawing wasn't fully working on mono on my Mac, and there were image loading issues with it)

As you've probably noticed, I've basically moved on from the project. All my day-job work is in Unity3D now. So please feel free to take the lead on the project. Anyone who is committing code is probably more qualified to make design decisions about the project.

Thanks! :D
